import type {
  CountryCode,
  CurrencyCode,
  CurrencyOption,
  ExchangeRates,
  PricingService,
} from "../types/pricing";

export const BASE_PRICE_PHP = 50_000;

export const PRICING_SERVICES: readonly PricingService[] = [
  { title: "Unlimited design and development revisions", icon: "revisions" },
  { title: "Mobile app design", icon: "mobile" },
  { title: "Website design and development", icon: "development" },
  { title: "Web design", icon: "web" },
  { title: "Product design", icon: "product" },
  { title: "UI/UX design", icon: "uiux" },
];

export const SUPPORTED_CURRENCIES: readonly CurrencyOption[] = [
  { code: "PHP", label: "Philippine peso", locale: "en-PH" },
  { code: "USD", label: "US dollar", locale: "en-US" },
  { code: "EUR", label: "Euro", locale: "en-IE" },
  { code: "GBP", label: "British pound", locale: "en-GB" },
  { code: "JPY", label: "Japanese yen", locale: "ja-JP" },
  { code: "AUD", label: "Australian dollar", locale: "en-AU" },
  { code: "CAD", label: "Canadian dollar", locale: "en-CA" },
  { code: "SGD", label: "Singapore dollar", locale: "en-SG" },
  { code: "KRW", label: "South Korean won", locale: "ko-KR" },
  { code: "CNY", label: "Chinese yuan", locale: "zh-CN" },
  { code: "INR", label: "Indian rupee", locale: "en-IN" },
  { code: "NZD", label: "New Zealand dollar", locale: "en-NZ" },
  { code: "CHF", label: "Swiss franc", locale: "de-CH" },
  { code: "HKD", label: "Hong Kong dollar", locale: "en-HK" },
  { code: "THB", label: "Thai baht", locale: "th-TH" },
  { code: "MYR", label: "Malaysian ringgit", locale: "ms-MY" },
  { code: "IDR", label: "Indonesian rupiah", locale: "id-ID" },
  { code: "AED", label: "UAE dirham", locale: "en-AE" },
  { code: "SAR", label: "Saudi riyal", locale: "ar-SA" },
  { code: "BRL", label: "Brazilian real", locale: "pt-BR" },
  { code: "MXN", label: "Mexican peso", locale: "es-MX" },
  { code: "ZAR", label: "South African rand", locale: "en-ZA" },
];

export const EU_COUNTRY_CODES = new Set<CountryCode>([
  "AT",
  "BE",
  "BG",
  "HR",
  "CY",
  "CZ",
  "DE",
  "DK",
  "EE",
  "ES",
  "FI",
  "FR",
  "GR",
  "HU",
  "IE",
  "IT",
  "LT",
  "LU",
  "LV",
  "MT",
  "NL",
  "PL",
  "PT",
  "RO",
  "SE",
  "SI",
  "SK",
]);

export const COUNTRY_TO_CURRENCY: Readonly<
  Partial<Record<CountryCode, CurrencyCode>>
> = {
  PH: "PHP",
  US: "USD",
  PR: "USD",
  JP: "JPY",
  GB: "GBP",
  GG: "GBP",
  IM: "GBP",
  JE: "GBP",
  AU: "AUD",
  CA: "CAD",
  SG: "SGD",
  KR: "KRW",
  CN: "CNY",
  IN: "INR",
  NZ: "NZD",
  CH: "CHF",
  LI: "CHF",
  HK: "HKD",
  TH: "THB",
  MY: "MYR",
  ID: "IDR",
  AE: "AED",
  SA: "SAR",
  BR: "BRL",
  MX: "MXN",
  ZA: "ZAR",
};

// Indicative fallbacks used only when the live rate service is unavailable.
// Keep all fallback values in this single file so they are easy to update.
export const STATIC_EXCHANGE_RATES: ExchangeRates = {
  PHP: 1,
  USD: 0.01631,
  EUR: 0.01431,
  GBP: 0.01234,
  JPY: 2.6368,
  AUD: 0.02363,
  CAD: 0.02313,
  SGD: 0.02111,
  KRW: 25.062,
  CNY: 0.11089,
  INR: 1.5399,
  NZD: 0.02887,
  CHF: 0.01319,
  HKD: 0.12792,
  THB: 0.5444,
  MYR: 0.06667,
  IDR: 291.31,
  AED: 0.0599,
  SAR: 0.06116,
  BRL: 0.08443,
  MXN: 0.28571,
  ZAR: 0.2685,
};
