import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../../components/Navbar";
import { Footer } from "../../components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div>
          <main className="relative overflow-hidden h-full py-32">
            {children}
          </main>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
